version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/ggabari/UdagramCI-CD/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-name:
    environment:
      My_ENV-Name: Me_Mario
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Leo!

workflows:
  my-custom-workflow:
    jobs:
      - my-name
