version: 2.1

jobs:
  build:
    docker:
      - image: circleci/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: circleci/base:stable
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/base:stable
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
